#!/bin/bash
# Push to GitHub default branch by entering 'p'
# Push to the upstream of a newly created branch using 'p head'
# Commit locally and don't push to the remote, with 'p commit'
# Get help by using 'p --help' or entering more than 1 argument

if [ $# -gt 1 ] || [[ $1 = '--help' ]]; then
	# Display Usage instruction if --help was the argument or if more than one arguments were passed
	echo -e "Usage:\t'./0-git_add'\tadd, commit and push to the default branch"
	echo -e "\t'./0-git_add head'\tpush to the new branch, create it if it's not available remotely"
	echo -e "\t'./0-git_add commit'\tadd and commit locally but don't push remotely"
	echo -e "\t'./0-git_add --help'\tdisplay help on usage"
	exit 0
fi

BRANCH=$1

echo -e "Enter the file to be pushed: \c"
read -e -r file

git add "$file"

echo -e "Commit Message (no quotes): \c"
read -e -r message

git commit -m "$message"

if [[ $BRANCH = 'head' ]]; then
	git push origin HEAD
	echo -e "\nExecuted 'git push origin HEAD'"
elif [[ $BRANCH = 'commit' ]]; then
	echo -e "\n'git push' not executed"
else
	git push
	echo -e "\nExecuted 'git push'"
fi
