#!/bin/bash

echo -e "Enter the file to be removed from git: \c"

read -e -r file

git rm $"$file"

echo -e "Commit Message (no quotation marks): \c"

read -e  -r message

git commit -m $"$message"

git push

