#!/bin/bash
# initialize a git repository and have it hosted automatically, having created the GitHub repository for it.
# Remember to:
#+	Replace [PAT] with your Personal Access Token
#+ 	Replace [USERNAME] with your GitHub username

GITREPO=$1

if [ $# -eq 1 ]; then	
	GITBRANCH="main"
elif [ $# -eq 2 ]; then
	GITBRANCH=$2
else
	echo -e "Usage:\t./7-create_git_repo <repository> <branch_name>"
	echo 'The second argument is optional and "main" by default'
	exit 1
fi

git init
git add .
git commit -m "initial commit"
git branch -M $GITBRANCH
git remote add origin https://[PAT]@github.com/[USERNAME]/$GITREPO.git
git push -u origin $GITBRANCH
