#!/bin/bash

echo -e "Enter the directory to be removed from git: \c"

read -e -r dir

git rm -r $"$dir"

echo -e "Commit Message (no quotation marks): \c"

read -e  -r commit

git commit -m $"$commit"

git push
